// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package gql

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// ArchiveIssueIssueArchiveIssueArchivePayload includes the requested fields of the GraphQL type IssueArchivePayload.
// The GraphQL type's documentation follows.
//
// A generic payload return from entity archive mutations.
type ArchiveIssueIssueArchiveIssueArchivePayload struct {
	// Whether the operation was successful.
	Success bool `json:"success"`
}

// GetSuccess returns ArchiveIssueIssueArchiveIssueArchivePayload.Success, and is useful for accessing the field via an interface.
func (v *ArchiveIssueIssueArchiveIssueArchivePayload) GetSuccess() bool { return v.Success }

// ArchiveIssueResponse is returned by ArchiveIssue on success.
type ArchiveIssueResponse struct {
	// Archives an issue.
	IssueArchive ArchiveIssueIssueArchiveIssueArchivePayload `json:"issueArchive"`
}

// GetIssueArchive returns ArchiveIssueResponse.IssueArchive, and is useful for accessing the field via an interface.
func (v *ArchiveIssueResponse) GetIssueArchive() ArchiveIssueIssueArchiveIssueArchivePayload {
	return v.IssueArchive
}

// CreateIssueIssueCreateIssuePayload includes the requested fields of the GraphQL type IssuePayload.
// The GraphQL type's documentation follows.
//
// The result of an issue mutation, containing the created or updated issue and a success indicator.
type CreateIssueIssueCreateIssuePayload struct {
	// Whether the operation was successful.
	Success bool `json:"success"`
	// The issue that was created or updated.
	Issue *CreateIssueIssueCreateIssuePayloadIssue `json:"issue"`
}

// GetSuccess returns CreateIssueIssueCreateIssuePayload.Success, and is useful for accessing the field via an interface.
func (v *CreateIssueIssueCreateIssuePayload) GetSuccess() bool { return v.Success }

// GetIssue returns CreateIssueIssueCreateIssuePayload.Issue, and is useful for accessing the field via an interface.
func (v *CreateIssueIssueCreateIssuePayload) GetIssue() *CreateIssueIssueCreateIssuePayloadIssue {
	return v.Issue
}

// CreateIssueIssueCreateIssuePayloadIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An issue is the core work item in Linear. Issues belong to a team, have a workflow status, can be assigned to users, carry a priority level, and can be organized into projects and cycles. Issues support sub-issues (parent-child hierarchy up to 10 levels deep), labels, due dates, estimates, and SLA tracking. They can also be linked to other issues via relations, attached to releases, and tracked through their full history of changes.
type CreateIssueIssueCreateIssuePayloadIssue struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// Issue's human readable identifier (e.g. ENG-123).
	Identifier string `json:"identifier"`
	// Issue URL.
	Url string `json:"url"`
	// The issue's title. This is the primary human-readable summary of the work item.
	Title string `json:"title"`
	// The team that the issue belongs to. Every issue must belong to exactly one team, which determines the available workflow states, labels, and other team-specific configuration.
	Team CreateIssueIssueCreateIssuePayloadIssueTeam `json:"team"`
}

// GetId returns CreateIssueIssueCreateIssuePayloadIssue.Id, and is useful for accessing the field via an interface.
func (v *CreateIssueIssueCreateIssuePayloadIssue) GetId() string { return v.Id }

// GetIdentifier returns CreateIssueIssueCreateIssuePayloadIssue.Identifier, and is useful for accessing the field via an interface.
func (v *CreateIssueIssueCreateIssuePayloadIssue) GetIdentifier() string { return v.Identifier }

// GetUrl returns CreateIssueIssueCreateIssuePayloadIssue.Url, and is useful for accessing the field via an interface.
func (v *CreateIssueIssueCreateIssuePayloadIssue) GetUrl() string { return v.Url }

// GetTitle returns CreateIssueIssueCreateIssuePayloadIssue.Title, and is useful for accessing the field via an interface.
func (v *CreateIssueIssueCreateIssuePayloadIssue) GetTitle() string { return v.Title }

// GetTeam returns CreateIssueIssueCreateIssuePayloadIssue.Team, and is useful for accessing the field via an interface.
func (v *CreateIssueIssueCreateIssuePayloadIssue) GetTeam() CreateIssueIssueCreateIssuePayloadIssueTeam {
	return v.Team
}

// CreateIssueIssueCreateIssuePayloadIssueTeam includes the requested fields of the GraphQL type Team.
// The GraphQL type's documentation follows.
//
// A team is the primary organizational unit in Linear. Issues belong to teams, and each team has its own workflow states, cycles, labels, and settings. Teams can be public (visible to all workspace members), private (visible only to team members), or restricted (visible only within an enclosing private-team boundary). Teams can also have sub-teams that inherit settings from their parent.
type CreateIssueIssueCreateIssuePayloadIssueTeam struct {
	// The team's unique key, used as a prefix in issue identifiers (e.g., 'ENG' in 'ENG-123') and in URLs.
	Key string `json:"key"`
}

// GetKey returns CreateIssueIssueCreateIssuePayloadIssueTeam.Key, and is useful for accessing the field via an interface.
func (v *CreateIssueIssueCreateIssuePayloadIssueTeam) GetKey() string { return v.Key }

// CreateIssueLabelIssueLabelCreateIssueLabelPayload includes the requested fields of the GraphQL type IssueLabelPayload.
// The GraphQL type's documentation follows.
//
// The result of a label mutation, containing the created or updated label and a success indicator.
type CreateIssueLabelIssueLabelCreateIssueLabelPayload struct {
	// Whether the operation was successful.
	Success bool `json:"success"`
	// The label that was created or updated.
	IssueLabel CreateIssueLabelIssueLabelCreateIssueLabelPayloadIssueLabel `json:"issueLabel"`
}

// GetSuccess returns CreateIssueLabelIssueLabelCreateIssueLabelPayload.Success, and is useful for accessing the field via an interface.
func (v *CreateIssueLabelIssueLabelCreateIssueLabelPayload) GetSuccess() bool { return v.Success }

// GetIssueLabel returns CreateIssueLabelIssueLabelCreateIssueLabelPayload.IssueLabel, and is useful for accessing the field via an interface.
func (v *CreateIssueLabelIssueLabelCreateIssueLabelPayload) GetIssueLabel() CreateIssueLabelIssueLabelCreateIssueLabelPayloadIssueLabel {
	return v.IssueLabel
}

// CreateIssueLabelIssueLabelCreateIssueLabelPayloadIssueLabel includes the requested fields of the GraphQL type IssueLabel.
// The GraphQL type's documentation follows.
//
// Labels that can be associated with issues. Labels help categorize and filter issues across a workspace. They can be workspace-level (shared across all teams) or team-scoped. Labels have a color for visual identification and can be organized hierarchically into groups, where a parent label acts as a group containing child labels. Labels may also be inherited from parent teams to sub-teams.
type CreateIssueLabelIssueLabelCreateIssueLabelPayloadIssueLabel struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// The label's name.
	Name string `json:"name"`
	// The label's color as a HEX string (e.g., '#EB5757'). Used for visual identification of the label in the UI.
	Color string `json:"color"`
	// The label's description.
	Description *string `json:"description"`
	// The team that the label is scoped to. If null, the label is a workspace-level label available to all teams in the workspace.
	Team *CreateIssueLabelIssueLabelCreateIssueLabelPayloadIssueLabelTeam `json:"team"`
}

// GetId returns CreateIssueLabelIssueLabelCreateIssueLabelPayloadIssueLabel.Id, and is useful for accessing the field via an interface.
func (v *CreateIssueLabelIssueLabelCreateIssueLabelPayloadIssueLabel) GetId() string { return v.Id }

// GetName returns CreateIssueLabelIssueLabelCreateIssueLabelPayloadIssueLabel.Name, and is useful for accessing the field via an interface.
func (v *CreateIssueLabelIssueLabelCreateIssueLabelPayloadIssueLabel) GetName() string { return v.Name }

// GetColor returns CreateIssueLabelIssueLabelCreateIssueLabelPayloadIssueLabel.Color, and is useful for accessing the field via an interface.
func (v *CreateIssueLabelIssueLabelCreateIssueLabelPayloadIssueLabel) GetColor() string {
	return v.Color
}

// GetDescription returns CreateIssueLabelIssueLabelCreateIssueLabelPayloadIssueLabel.Description, and is useful for accessing the field via an interface.
func (v *CreateIssueLabelIssueLabelCreateIssueLabelPayloadIssueLabel) GetDescription() *string {
	return v.Description
}

// GetTeam returns CreateIssueLabelIssueLabelCreateIssueLabelPayloadIssueLabel.Team, and is useful for accessing the field via an interface.
func (v *CreateIssueLabelIssueLabelCreateIssueLabelPayloadIssueLabel) GetTeam() *CreateIssueLabelIssueLabelCreateIssueLabelPayloadIssueLabelTeam {
	return v.Team
}

// CreateIssueLabelIssueLabelCreateIssueLabelPayloadIssueLabelTeam includes the requested fields of the GraphQL type Team.
// The GraphQL type's documentation follows.
//
// A team is the primary organizational unit in Linear. Issues belong to teams, and each team has its own workflow states, cycles, labels, and settings. Teams can be public (visible to all workspace members), private (visible only to team members), or restricted (visible only within an enclosing private-team boundary). Teams can also have sub-teams that inherit settings from their parent.
type CreateIssueLabelIssueLabelCreateIssueLabelPayloadIssueLabelTeam struct {
	// The team's unique key, used as a prefix in issue identifiers (e.g., 'ENG' in 'ENG-123') and in URLs.
	Key string `json:"key"`
	// The team's name.
	Name string `json:"name"`
}

// GetKey returns CreateIssueLabelIssueLabelCreateIssueLabelPayloadIssueLabelTeam.Key, and is useful for accessing the field via an interface.
func (v *CreateIssueLabelIssueLabelCreateIssueLabelPayloadIssueLabelTeam) GetKey() string {
	return v.Key
}

// GetName returns CreateIssueLabelIssueLabelCreateIssueLabelPayloadIssueLabelTeam.Name, and is useful for accessing the field via an interface.
func (v *CreateIssueLabelIssueLabelCreateIssueLabelPayloadIssueLabelTeam) GetName() string {
	return v.Name
}

// CreateIssueLabelResponse is returned by CreateIssueLabel on success.
type CreateIssueLabelResponse struct {
	// Creates a new label.
	IssueLabelCreate CreateIssueLabelIssueLabelCreateIssueLabelPayload `json:"issueLabelCreate"`
}

// GetIssueLabelCreate returns CreateIssueLabelResponse.IssueLabelCreate, and is useful for accessing the field via an interface.
func (v *CreateIssueLabelResponse) GetIssueLabelCreate() CreateIssueLabelIssueLabelCreateIssueLabelPayload {
	return v.IssueLabelCreate
}

// CreateIssueResponse is returned by CreateIssue on success.
type CreateIssueResponse struct {
	// Creates a new issue.
	IssueCreate CreateIssueIssueCreateIssuePayload `json:"issueCreate"`
}

// GetIssueCreate returns CreateIssueResponse.IssueCreate, and is useful for accessing the field via an interface.
func (v *CreateIssueResponse) GetIssueCreate() CreateIssueIssueCreateIssuePayload {
	return v.IssueCreate
}

// CreateTeamResponse is returned by CreateTeam on success.
type CreateTeamResponse struct {
	// Creates a new team. The user who creates the team will automatically be added as a member and owner of the newly created team. Default workflow states, labels, and other team resources are created alongside the team.
	TeamCreate CreateTeamTeamCreateTeamPayload `json:"teamCreate"`
}

// GetTeamCreate returns CreateTeamResponse.TeamCreate, and is useful for accessing the field via an interface.
func (v *CreateTeamResponse) GetTeamCreate() CreateTeamTeamCreateTeamPayload { return v.TeamCreate }

// CreateTeamTeamCreateTeamPayload includes the requested fields of the GraphQL type TeamPayload.
// The GraphQL type's documentation follows.
//
// Team operation response.
type CreateTeamTeamCreateTeamPayload struct {
	// Whether the operation was successful.
	Success bool `json:"success"`
	// The team that was created or updated.
	Team *CreateTeamTeamCreateTeamPayloadTeam `json:"team"`
}

// GetSuccess returns CreateTeamTeamCreateTeamPayload.Success, and is useful for accessing the field via an interface.
func (v *CreateTeamTeamCreateTeamPayload) GetSuccess() bool { return v.Success }

// GetTeam returns CreateTeamTeamCreateTeamPayload.Team, and is useful for accessing the field via an interface.
func (v *CreateTeamTeamCreateTeamPayload) GetTeam() *CreateTeamTeamCreateTeamPayloadTeam {
	return v.Team
}

// CreateTeamTeamCreateTeamPayloadTeam includes the requested fields of the GraphQL type Team.
// The GraphQL type's documentation follows.
//
// A team is the primary organizational unit in Linear. Issues belong to teams, and each team has its own workflow states, cycles, labels, and settings. Teams can be public (visible to all workspace members), private (visible only to team members), or restricted (visible only within an enclosing private-team boundary). Teams can also have sub-teams that inherit settings from their parent.
type CreateTeamTeamCreateTeamPayloadTeam struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// The team's unique key, used as a prefix in issue identifiers (e.g., 'ENG' in 'ENG-123') and in URLs.
	Key string `json:"key"`
	// The team's name.
	Name string `json:"name"`
}

// GetId returns CreateTeamTeamCreateTeamPayloadTeam.Id, and is useful for accessing the field via an interface.
func (v *CreateTeamTeamCreateTeamPayloadTeam) GetId() string { return v.Id }

// GetKey returns CreateTeamTeamCreateTeamPayloadTeam.Key, and is useful for accessing the field via an interface.
func (v *CreateTeamTeamCreateTeamPayloadTeam) GetKey() string { return v.Key }

// GetName returns CreateTeamTeamCreateTeamPayloadTeam.Name, and is useful for accessing the field via an interface.
func (v *CreateTeamTeamCreateTeamPayloadTeam) GetName() string { return v.Name }

// GetIssueDetailsIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An issue is the core work item in Linear. Issues belong to a team, have a workflow status, can be assigned to users, carry a priority level, and can be organized into projects and cycles. Issues support sub-issues (parent-child hierarchy up to 10 levels deep), labels, due dates, estimates, and SLA tracking. They can also be linked to other issues via relations, attached to releases, and tracked through their full history of changes.
type GetIssueDetailsIssue struct {
	// Issue's human readable identifier (e.g. ENG-123).
	Identifier string `json:"identifier"`
	// The issue's title. This is the primary human-readable summary of the work item.
	Title string `json:"title"`
	// The issue's description in markdown format.
	Description *string `json:"description"`
	// Issue URL.
	Url string `json:"url"`
	// Suggested branch name for the issue.
	BranchName string `json:"branchName"`
	// The workflow state (issue status) that the issue is currently in. Workflow states represent the issue's progress through the team's workflow, such as Triage, Todo, In Progress, Done, or Canceled.
	State GetIssueDetailsIssueStateWorkflowState `json:"state"`
	// The user to whom the issue is assigned. Null if the issue is unassigned.
	Assignee *GetIssueDetailsIssueAssigneeUser `json:"assignee"`
	// The priority of the issue. 0 = No priority, 1 = Urgent, 2 = High, 3 = Medium, 4 = Low.
	Priority float64 `json:"priority"`
	// The project that the issue is associated with. Null if the issue is not part of any project.
	Project *GetIssueDetailsIssueProject `json:"project"`
	// The project milestone that the issue is associated with. Null if the issue is not assigned to a specific milestone within its project.
	ProjectMilestone *GetIssueDetailsIssueProjectMilestone `json:"projectMilestone"`
	// The cycle that the issue is associated with. Null if the issue is not part of any cycle.
	Cycle *GetIssueDetailsIssueCycle `json:"cycle"`
	// The team that the issue belongs to. Every issue must belong to exactly one team, which determines the available workflow states, labels, and other team-specific configuration.
	Team GetIssueDetailsIssueTeam `json:"team"`
	// Labels associated with this issue.
	Labels GetIssueDetailsIssueLabelsIssueLabelConnection `json:"labels"`
	// The parent of the issue.
	Parent *GetIssueDetailsIssueParentIssue `json:"parent"`
	// Children of the issue.
	Children GetIssueDetailsIssueChildrenIssueConnection `json:"children"`
	// Attachments associated with the issue.
	Attachments GetIssueDetailsIssueAttachmentsAttachmentConnection `json:"attachments"`
	// Documents associated with the issue.
	Documents GetIssueDetailsIssueDocumentsDocumentConnection `json:"documents"`
}

// GetIdentifier returns GetIssueDetailsIssue.Identifier, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssue) GetIdentifier() string { return v.Identifier }

// GetTitle returns GetIssueDetailsIssue.Title, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssue) GetTitle() string { return v.Title }

// GetDescription returns GetIssueDetailsIssue.Description, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssue) GetDescription() *string { return v.Description }

// GetUrl returns GetIssueDetailsIssue.Url, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssue) GetUrl() string { return v.Url }

// GetBranchName returns GetIssueDetailsIssue.BranchName, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssue) GetBranchName() string { return v.BranchName }

// GetState returns GetIssueDetailsIssue.State, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssue) GetState() GetIssueDetailsIssueStateWorkflowState { return v.State }

// GetAssignee returns GetIssueDetailsIssue.Assignee, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssue) GetAssignee() *GetIssueDetailsIssueAssigneeUser { return v.Assignee }

// GetPriority returns GetIssueDetailsIssue.Priority, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssue) GetPriority() float64 { return v.Priority }

// GetProject returns GetIssueDetailsIssue.Project, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssue) GetProject() *GetIssueDetailsIssueProject { return v.Project }

// GetProjectMilestone returns GetIssueDetailsIssue.ProjectMilestone, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssue) GetProjectMilestone() *GetIssueDetailsIssueProjectMilestone {
	return v.ProjectMilestone
}

// GetCycle returns GetIssueDetailsIssue.Cycle, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssue) GetCycle() *GetIssueDetailsIssueCycle { return v.Cycle }

// GetTeam returns GetIssueDetailsIssue.Team, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssue) GetTeam() GetIssueDetailsIssueTeam { return v.Team }

// GetLabels returns GetIssueDetailsIssue.Labels, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssue) GetLabels() GetIssueDetailsIssueLabelsIssueLabelConnection {
	return v.Labels
}

// GetParent returns GetIssueDetailsIssue.Parent, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssue) GetParent() *GetIssueDetailsIssueParentIssue { return v.Parent }

// GetChildren returns GetIssueDetailsIssue.Children, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssue) GetChildren() GetIssueDetailsIssueChildrenIssueConnection {
	return v.Children
}

// GetAttachments returns GetIssueDetailsIssue.Attachments, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssue) GetAttachments() GetIssueDetailsIssueAttachmentsAttachmentConnection {
	return v.Attachments
}

// GetDocuments returns GetIssueDetailsIssue.Documents, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssue) GetDocuments() GetIssueDetailsIssueDocumentsDocumentConnection {
	return v.Documents
}

// GetIssueDetailsIssueAssigneeUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user that belongs to a workspace. Users can have different roles (admin, member, guest, or app) that determine their level of access. Users can be members of multiple teams, and can be active or deactivated. Guest users have limited access scoped to specific teams they are invited to.
type GetIssueDetailsIssueAssigneeUser struct {
	// The user's full name.
	Name string `json:"name"`
	// The user's display (nick) name. Must be unique within the workspace.
	DisplayName string `json:"displayName"`
}

// GetName returns GetIssueDetailsIssueAssigneeUser.Name, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueAssigneeUser) GetName() string { return v.Name }

// GetDisplayName returns GetIssueDetailsIssueAssigneeUser.DisplayName, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueAssigneeUser) GetDisplayName() string { return v.DisplayName }

// GetIssueDetailsIssueAttachmentsAttachmentConnection includes the requested fields of the GraphQL type AttachmentConnection.
type GetIssueDetailsIssueAttachmentsAttachmentConnection struct {
	Nodes []GetIssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment `json:"nodes"`
}

// GetNodes returns GetIssueDetailsIssueAttachmentsAttachmentConnection.Nodes, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueAttachmentsAttachmentConnection) GetNodes() []GetIssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment {
	return v.Nodes
}

// GetIssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment includes the requested fields of the GraphQL type Attachment.
// The GraphQL type's documentation follows.
//
// An attachment linking external content to an issue. Attachments represent connections to external resources such as GitHub pull requests, Slack messages, Zendesk tickets, Figma files, Sentry issues, Intercom conversations, and plain URLs. Each attachment has a title and subtitle displayed in the Linear UI, a URL serving as both the link destination and unique identifier per issue, and optional metadata specific to the source integration.
type GetIssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// Content for the title line in the Linear attachment widget.
	Title string `json:"title"`
	// The URL of the external resource this attachment links to. Also serves as a unique identifier for the attachment within an issue; no two attachments on the same issue can share the same URL.
	Url string `json:"url"`
	// Content for the subtitle line in the Linear attachment widget.
	Subtitle *string `json:"subtitle"`
	// The source type of the attachment, derived from the source metadata. Returns the integration type (e.g., 'github', 'slack', 'zendesk') or 'unknown' if no source is set.
	SourceType *string `json:"sourceType"`
	// Integration-specific metadata for this attachment. The schema varies by source type and may include fields such as pull request status, review counts, commit information, ticket status, or other data from the external system.
	Metadata map[string]any `json:"metadata"`
	// The time at which the entity was created.
	CreatedAt string `json:"createdAt"`
}

// GetId returns GetIssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment.Id, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment) GetId() string {
	return v.Id
}

// GetTitle returns GetIssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment.Title, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment) GetTitle() string {
	return v.Title
}

// GetUrl returns GetIssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment.Url, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment) GetUrl() string {
	return v.Url
}

// GetSubtitle returns GetIssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment.Subtitle, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment) GetSubtitle() *string {
	return v.Subtitle
}

// GetSourceType returns GetIssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment.SourceType, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment) GetSourceType() *string {
	return v.SourceType
}

// GetMetadata returns GetIssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment.Metadata, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment) GetMetadata() map[string]any {
	return v.Metadata
}

// GetCreatedAt returns GetIssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment.CreatedAt, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueAttachmentsAttachmentConnectionNodesAttachment) GetCreatedAt() string {
	return v.CreatedAt
}

// GetIssueDetailsIssueChildrenIssueConnection includes the requested fields of the GraphQL type IssueConnection.
type GetIssueDetailsIssueChildrenIssueConnection struct {
	Nodes []GetIssueDetailsIssueChildrenIssueConnectionNodesIssue `json:"nodes"`
}

// GetNodes returns GetIssueDetailsIssueChildrenIssueConnection.Nodes, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueChildrenIssueConnection) GetNodes() []GetIssueDetailsIssueChildrenIssueConnectionNodesIssue {
	return v.Nodes
}

// GetIssueDetailsIssueChildrenIssueConnectionNodesIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An issue is the core work item in Linear. Issues belong to a team, have a workflow status, can be assigned to users, carry a priority level, and can be organized into projects and cycles. Issues support sub-issues (parent-child hierarchy up to 10 levels deep), labels, due dates, estimates, and SLA tracking. They can also be linked to other issues via relations, attached to releases, and tracked through their full history of changes.
type GetIssueDetailsIssueChildrenIssueConnectionNodesIssue struct {
	// Issue's human readable identifier (e.g. ENG-123).
	Identifier string `json:"identifier"`
	// The issue's title. This is the primary human-readable summary of the work item.
	Title string `json:"title"`
	// The workflow state (issue status) that the issue is currently in. Workflow states represent the issue's progress through the team's workflow, such as Triage, Todo, In Progress, Done, or Canceled.
	State GetIssueDetailsIssueChildrenIssueConnectionNodesIssueStateWorkflowState `json:"state"`
}

// GetIdentifier returns GetIssueDetailsIssueChildrenIssueConnectionNodesIssue.Identifier, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueChildrenIssueConnectionNodesIssue) GetIdentifier() string {
	return v.Identifier
}

// GetTitle returns GetIssueDetailsIssueChildrenIssueConnectionNodesIssue.Title, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueChildrenIssueConnectionNodesIssue) GetTitle() string { return v.Title }

// GetState returns GetIssueDetailsIssueChildrenIssueConnectionNodesIssue.State, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueChildrenIssueConnectionNodesIssue) GetState() GetIssueDetailsIssueChildrenIssueConnectionNodesIssueStateWorkflowState {
	return v.State
}

// GetIssueDetailsIssueChildrenIssueConnectionNodesIssueStateWorkflowState includes the requested fields of the GraphQL type WorkflowState.
// The GraphQL type's documentation follows.
//
// A state in a team's workflow, representing an issue status such as Triage, Backlog, Todo, In Progress, In Review, Done, or Canceled. Each team has its own set of workflow states that define the progression of issues through the team's process. Workflow states have a type that categorizes them (triage, backlog, unstarted, started, completed, canceled), a position that determines their display order, and a color for visual identification. States can be inherited from parent teams to sub-teams.
type GetIssueDetailsIssueChildrenIssueConnectionNodesIssueStateWorkflowState struct {
	// The state's human-readable name (e.g., 'In Progress', 'Done', 'Backlog').
	Name string `json:"name"`
	// The state's UI color as a HEX string.
	Color string `json:"color"`
}

// GetName returns GetIssueDetailsIssueChildrenIssueConnectionNodesIssueStateWorkflowState.Name, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueChildrenIssueConnectionNodesIssueStateWorkflowState) GetName() string {
	return v.Name
}

// GetColor returns GetIssueDetailsIssueChildrenIssueConnectionNodesIssueStateWorkflowState.Color, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueChildrenIssueConnectionNodesIssueStateWorkflowState) GetColor() string {
	return v.Color
}

// GetIssueDetailsIssueCycle includes the requested fields of the GraphQL type Cycle.
// The GraphQL type's documentation follows.
//
// A time-boxed iteration (similar to a sprint) used for planning and tracking work. Cycles belong to a team and have defined start and end dates. Issues are assigned to cycles for time-based planning, and progress is tracked via completed, in-progress, and total scope. Cycles are automatically completed when their end date passes, and uncompleted issues can be carried over to the next cycle.
type GetIssueDetailsIssueCycle struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// The auto-incrementing number of the cycle, unique within its team. This value is assigned automatically by the database and cannot be set on creation.
	Number float64 `json:"number"`
	// The custom name of the cycle. If not set, the cycle is displayed using its number (e.g., "Cycle 5").
	Name *string `json:"name"`
	// Whether the cycle is currently active. A cycle is active if the current time is between its start and end dates and it has not been completed.
	IsActive bool `json:"isActive"`
	// Whether this cycle is the next upcoming (not yet started) cycle for the team.
	IsNext bool `json:"isNext"`
	// Whether this cycle is the most recently completed cycle for the team.
	IsPrevious bool `json:"isPrevious"`
	// Whether the cycle has not yet started. True if the cycle's start date is in the future.
	IsFuture bool `json:"isFuture"`
	// Whether the cycle's end date has passed.
	IsPast bool `json:"isPast"`
}

// GetId returns GetIssueDetailsIssueCycle.Id, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueCycle) GetId() string { return v.Id }

// GetNumber returns GetIssueDetailsIssueCycle.Number, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueCycle) GetNumber() float64 { return v.Number }

// GetName returns GetIssueDetailsIssueCycle.Name, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueCycle) GetName() *string { return v.Name }

// GetIsActive returns GetIssueDetailsIssueCycle.IsActive, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueCycle) GetIsActive() bool { return v.IsActive }

// GetIsNext returns GetIssueDetailsIssueCycle.IsNext, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueCycle) GetIsNext() bool { return v.IsNext }

// GetIsPrevious returns GetIssueDetailsIssueCycle.IsPrevious, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueCycle) GetIsPrevious() bool { return v.IsPrevious }

// GetIsFuture returns GetIssueDetailsIssueCycle.IsFuture, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueCycle) GetIsFuture() bool { return v.IsFuture }

// GetIsPast returns GetIssueDetailsIssueCycle.IsPast, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueCycle) GetIsPast() bool { return v.IsPast }

// GetIssueDetailsIssueDocumentsDocumentConnection includes the requested fields of the GraphQL type DocumentConnection.
type GetIssueDetailsIssueDocumentsDocumentConnection struct {
	Nodes []GetIssueDetailsIssueDocumentsDocumentConnectionNodesDocument `json:"nodes"`
}

// GetNodes returns GetIssueDetailsIssueDocumentsDocumentConnection.Nodes, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueDocumentsDocumentConnection) GetNodes() []GetIssueDetailsIssueDocumentsDocumentConnectionNodesDocument {
	return v.Nodes
}

// GetIssueDetailsIssueDocumentsDocumentConnectionNodesDocument includes the requested fields of the GraphQL type Document.
// The GraphQL type's documentation follows.
//
// A rich-text document that lives within a project, initiative, team, issue, release, or cycle. Documents support collaborative editing via ProseMirror/Yjs and store their content in a separate DocumentContent entity. Each document is associated with exactly one parent entity.
type GetIssueDetailsIssueDocumentsDocumentConnectionNodesDocument struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// The title of the document. An empty string indicates an untitled document.
	Title string `json:"title"`
	// The document's unique URL slug, used to construct human-readable URLs.
	SlugId string `json:"slugId"`
	// The canonical url for the document.
	Url string `json:"url"`
	// The time at which the entity was created.
	CreatedAt string `json:"createdAt"`
	// The last time at which the entity was meaningfully updated. This is the same as the creation time if the entity hasn't
	// been updated after creation.
	UpdatedAt string `json:"updatedAt"`
}

// GetId returns GetIssueDetailsIssueDocumentsDocumentConnectionNodesDocument.Id, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueDocumentsDocumentConnectionNodesDocument) GetId() string { return v.Id }

// GetTitle returns GetIssueDetailsIssueDocumentsDocumentConnectionNodesDocument.Title, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueDocumentsDocumentConnectionNodesDocument) GetTitle() string {
	return v.Title
}

// GetSlugId returns GetIssueDetailsIssueDocumentsDocumentConnectionNodesDocument.SlugId, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueDocumentsDocumentConnectionNodesDocument) GetSlugId() string {
	return v.SlugId
}

// GetUrl returns GetIssueDetailsIssueDocumentsDocumentConnectionNodesDocument.Url, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueDocumentsDocumentConnectionNodesDocument) GetUrl() string { return v.Url }

// GetCreatedAt returns GetIssueDetailsIssueDocumentsDocumentConnectionNodesDocument.CreatedAt, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueDocumentsDocumentConnectionNodesDocument) GetCreatedAt() string {
	return v.CreatedAt
}

// GetUpdatedAt returns GetIssueDetailsIssueDocumentsDocumentConnectionNodesDocument.UpdatedAt, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueDocumentsDocumentConnectionNodesDocument) GetUpdatedAt() string {
	return v.UpdatedAt
}

// GetIssueDetailsIssueLabelsIssueLabelConnection includes the requested fields of the GraphQL type IssueLabelConnection.
type GetIssueDetailsIssueLabelsIssueLabelConnection struct {
	Nodes []GetIssueDetailsIssueLabelsIssueLabelConnectionNodesIssueLabel `json:"nodes"`
}

// GetNodes returns GetIssueDetailsIssueLabelsIssueLabelConnection.Nodes, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueLabelsIssueLabelConnection) GetNodes() []GetIssueDetailsIssueLabelsIssueLabelConnectionNodesIssueLabel {
	return v.Nodes
}

// GetIssueDetailsIssueLabelsIssueLabelConnectionNodesIssueLabel includes the requested fields of the GraphQL type IssueLabel.
// The GraphQL type's documentation follows.
//
// Labels that can be associated with issues. Labels help categorize and filter issues across a workspace. They can be workspace-level (shared across all teams) or team-scoped. Labels have a color for visual identification and can be organized hierarchically into groups, where a parent label acts as a group containing child labels. Labels may also be inherited from parent teams to sub-teams.
type GetIssueDetailsIssueLabelsIssueLabelConnectionNodesIssueLabel struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// The label's name.
	Name string `json:"name"`
	// The label's color as a HEX string (e.g., '#EB5757'). Used for visual identification of the label in the UI.
	Color string `json:"color"`
}

// GetId returns GetIssueDetailsIssueLabelsIssueLabelConnectionNodesIssueLabel.Id, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueLabelsIssueLabelConnectionNodesIssueLabel) GetId() string { return v.Id }

// GetName returns GetIssueDetailsIssueLabelsIssueLabelConnectionNodesIssueLabel.Name, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueLabelsIssueLabelConnectionNodesIssueLabel) GetName() string {
	return v.Name
}

// GetColor returns GetIssueDetailsIssueLabelsIssueLabelConnectionNodesIssueLabel.Color, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueLabelsIssueLabelConnectionNodesIssueLabel) GetColor() string {
	return v.Color
}

// GetIssueDetailsIssueParentIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An issue is the core work item in Linear. Issues belong to a team, have a workflow status, can be assigned to users, carry a priority level, and can be organized into projects and cycles. Issues support sub-issues (parent-child hierarchy up to 10 levels deep), labels, due dates, estimates, and SLA tracking. They can also be linked to other issues via relations, attached to releases, and tracked through their full history of changes.
type GetIssueDetailsIssueParentIssue struct {
	// Issue's human readable identifier (e.g. ENG-123).
	Identifier string `json:"identifier"`
	// The issue's title. This is the primary human-readable summary of the work item.
	Title string `json:"title"`
	// The workflow state (issue status) that the issue is currently in. Workflow states represent the issue's progress through the team's workflow, such as Triage, Todo, In Progress, Done, or Canceled.
	State GetIssueDetailsIssueParentIssueStateWorkflowState `json:"state"`
}

// GetIdentifier returns GetIssueDetailsIssueParentIssue.Identifier, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueParentIssue) GetIdentifier() string { return v.Identifier }

// GetTitle returns GetIssueDetailsIssueParentIssue.Title, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueParentIssue) GetTitle() string { return v.Title }

// GetState returns GetIssueDetailsIssueParentIssue.State, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueParentIssue) GetState() GetIssueDetailsIssueParentIssueStateWorkflowState {
	return v.State
}

// GetIssueDetailsIssueParentIssueStateWorkflowState includes the requested fields of the GraphQL type WorkflowState.
// The GraphQL type's documentation follows.
//
// A state in a team's workflow, representing an issue status such as Triage, Backlog, Todo, In Progress, In Review, Done, or Canceled. Each team has its own set of workflow states that define the progression of issues through the team's process. Workflow states have a type that categorizes them (triage, backlog, unstarted, started, completed, canceled), a position that determines their display order, and a color for visual identification. States can be inherited from parent teams to sub-teams.
type GetIssueDetailsIssueParentIssueStateWorkflowState struct {
	// The state's human-readable name (e.g., 'In Progress', 'Done', 'Backlog').
	Name string `json:"name"`
	// The state's UI color as a HEX string.
	Color string `json:"color"`
}

// GetName returns GetIssueDetailsIssueParentIssueStateWorkflowState.Name, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueParentIssueStateWorkflowState) GetName() string { return v.Name }

// GetColor returns GetIssueDetailsIssueParentIssueStateWorkflowState.Color, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueParentIssueStateWorkflowState) GetColor() string { return v.Color }

// GetIssueDetailsIssueProject includes the requested fields of the GraphQL type Project.
// The GraphQL type's documentation follows.
//
// A project is a collection of issues working toward a shared goal. Projects have start and target dates, milestones, status tracking, and progress metrics. They can span multiple teams and be grouped under initiatives.
type GetIssueDetailsIssueProject struct {
	// The name of the project.
	Name string `json:"name"`
}

// GetName returns GetIssueDetailsIssueProject.Name, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueProject) GetName() string { return v.Name }

// GetIssueDetailsIssueProjectMilestone includes the requested fields of the GraphQL type ProjectMilestone.
// The GraphQL type's documentation follows.
//
// A milestone within a project. Milestones break a project into phases or target checkpoints, each with its own target date and set of issues. Issues can be assigned to a milestone to track progress toward that checkpoint.
type GetIssueDetailsIssueProjectMilestone struct {
	// The name of the project milestone.
	Name string `json:"name"`
}

// GetName returns GetIssueDetailsIssueProjectMilestone.Name, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueProjectMilestone) GetName() string { return v.Name }

// GetIssueDetailsIssueStateWorkflowState includes the requested fields of the GraphQL type WorkflowState.
// The GraphQL type's documentation follows.
//
// A state in a team's workflow, representing an issue status such as Triage, Backlog, Todo, In Progress, In Review, Done, or Canceled. Each team has its own set of workflow states that define the progression of issues through the team's process. Workflow states have a type that categorizes them (triage, backlog, unstarted, started, completed, canceled), a position that determines their display order, and a color for visual identification. States can be inherited from parent teams to sub-teams.
type GetIssueDetailsIssueStateWorkflowState struct {
	// The state's human-readable name (e.g., 'In Progress', 'Done', 'Backlog').
	Name string `json:"name"`
	// The state's UI color as a HEX string.
	Color string `json:"color"`
}

// GetName returns GetIssueDetailsIssueStateWorkflowState.Name, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueStateWorkflowState) GetName() string { return v.Name }

// GetColor returns GetIssueDetailsIssueStateWorkflowState.Color, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueStateWorkflowState) GetColor() string { return v.Color }

// GetIssueDetailsIssueTeam includes the requested fields of the GraphQL type Team.
// The GraphQL type's documentation follows.
//
// A team is the primary organizational unit in Linear. Issues belong to teams, and each team has its own workflow states, cycles, labels, and settings. Teams can be public (visible to all workspace members), private (visible only to team members), or restricted (visible only within an enclosing private-team boundary). Teams can also have sub-teams that inherit settings from their parent.
type GetIssueDetailsIssueTeam struct {
	// Team's currently active cycle.
	ActiveCycle *GetIssueDetailsIssueTeamActiveCycle `json:"activeCycle"`
}

// GetActiveCycle returns GetIssueDetailsIssueTeam.ActiveCycle, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueTeam) GetActiveCycle() *GetIssueDetailsIssueTeamActiveCycle {
	return v.ActiveCycle
}

// GetIssueDetailsIssueTeamActiveCycle includes the requested fields of the GraphQL type Cycle.
// The GraphQL type's documentation follows.
//
// A time-boxed iteration (similar to a sprint) used for planning and tracking work. Cycles belong to a team and have defined start and end dates. Issues are assigned to cycles for time-based planning, and progress is tracked via completed, in-progress, and total scope. Cycles are automatically completed when their end date passes, and uncompleted issues can be carried over to the next cycle.
type GetIssueDetailsIssueTeamActiveCycle struct {
	// The auto-incrementing number of the cycle, unique within its team. This value is assigned automatically by the database and cannot be set on creation.
	Number float64 `json:"number"`
}

// GetNumber returns GetIssueDetailsIssueTeamActiveCycle.Number, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsIssueTeamActiveCycle) GetNumber() float64 { return v.Number }

// GetIssueDetailsResponse is returned by GetIssueDetails on success.
type GetIssueDetailsResponse struct {
	// One specific issue, looked up by its unique identifier.
	Issue GetIssueDetailsIssue `json:"issue"`
}

// GetIssue returns GetIssueDetailsResponse.Issue, and is useful for accessing the field via an interface.
func (v *GetIssueDetailsResponse) GetIssue() GetIssueDetailsIssue { return v.Issue }

// GetIssueTitleURLIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An issue is the core work item in Linear. Issues belong to a team, have a workflow status, can be assigned to users, carry a priority level, and can be organized into projects and cycles. Issues support sub-issues (parent-child hierarchy up to 10 levels deep), labels, due dates, estimates, and SLA tracking. They can also be linked to other issues via relations, attached to releases, and tracked through their full history of changes.
type GetIssueTitleURLIssue struct {
	// The issue's title. This is the primary human-readable summary of the work item.
	Title string `json:"title"`
	// Issue URL.
	Url string `json:"url"`
	// Issue's human readable identifier (e.g. ENG-123).
	Identifier string `json:"identifier"`
}

// GetTitle returns GetIssueTitleURLIssue.Title, and is useful for accessing the field via an interface.
func (v *GetIssueTitleURLIssue) GetTitle() string { return v.Title }

// GetUrl returns GetIssueTitleURLIssue.Url, and is useful for accessing the field via an interface.
func (v *GetIssueTitleURLIssue) GetUrl() string { return v.Url }

// GetIdentifier returns GetIssueTitleURLIssue.Identifier, and is useful for accessing the field via an interface.
func (v *GetIssueTitleURLIssue) GetIdentifier() string { return v.Identifier }

// GetIssueTitleURLResponse is returned by GetIssueTitleURL on success.
type GetIssueTitleURLResponse struct {
	// One specific issue, looked up by its unique identifier.
	Issue GetIssueTitleURLIssue `json:"issue"`
}

// GetIssue returns GetIssueTitleURLResponse.Issue, and is useful for accessing the field via an interface.
func (v *GetIssueTitleURLResponse) GetIssue() GetIssueTitleURLIssue { return v.Issue }

// Input for creating a new issue. At minimum, a team must be specified. A title is required unless a template is provided. All other fields are optional and will use defaults from the team or template if not specified.
type IssueCreateInput struct {
	// The identifier of the user to assign the issue to.
	AssigneeId *string `json:"assigneeId"`
	// The time at which the issue was completed (e.g. if importing from another system). Must be a time in the past and after createdAt. Cannot be provided with an incompatible workflow state.
	CompletedAt *string `json:"completedAt"`
	// Create issue as a user with the provided name. This option is only available to OAuth applications creating issues in `actor=app` mode.
	CreateAsUser *string `json:"createAsUser"`
	// The time at which the issue was created (e.g. if importing from another system). Must be a time in the past. If none is provided, the backend will generate the time as now.
	CreatedAt *string `json:"createdAt"`
	// The cycle associated with the issue.
	CycleId *string `json:"cycleId"`
	// The identifier of the agent user to delegate the issue to.
	DelegateId *string `json:"delegateId"`
	// The issue description in markdown format.
	Description *string `json:"description"`
	// [Internal] The issue description as a Prosemirror document.
	DescriptionData *any `json:"descriptionData"`
	// Provide an external user avatar URL. Can only be used in conjunction with the `createAsUser` options. This option is only available to OAuth applications creating comments in `actor=app` mode.
	DisplayIconUrl *string `json:"displayIconUrl"`
	// The date at which the issue is due.
	DueDate *string `json:"dueDate"`
	// The estimated complexity of the issue.
	Estimate *int `json:"estimate"`
	// The identifier in UUID v4 format. If none is provided, the backend will generate one.
	Id *string `json:"id"`
	// [Internal] Whether this issue should inherit shared access from its parent issue. Set to false to opt out of automatic shared access inheritance when creating a sub-issue.
	InheritsSharedAccess *bool `json:"inheritsSharedAccess"`
	// The identifiers of the issue labels associated with this ticket.
	LabelIds []string `json:"labelIds"`
	// The ID of the last template applied to the issue.
	LastAppliedTemplateId *string `json:"lastAppliedTemplateId"`
	// The identifier of the parent issue. Can be a UUID or issue identifier (e.g., 'LIN-123').
	ParentId *string `json:"parentId"`
	// Whether the passed sort order should be preserved.
	PreserveSortOrderOnCreate *bool `json:"preserveSortOrderOnCreate"`
	// The priority of the issue. 0 = No priority, 1 = Urgent, 2 = High, 3 = Medium, 4 = Low.
	Priority *int `json:"priority"`
	// The position of the issue related to other issues, when ordered by priority.
	PrioritySortOrder *float64 `json:"prioritySortOrder"`
	// The project associated with the issue.
	ProjectId *string `json:"projectId"`
	// The project milestone associated with the issue.
	ProjectMilestoneId *string `json:"projectMilestoneId"`
	// The comment the issue is referencing.
	ReferenceCommentId *string `json:"referenceCommentId"`
	// The identifiers of the releases to associate with this issue.
	ReleaseIds []string `json:"releaseIds"`
	// [Internal] The time at which an issue will be considered in breach of SLA.
	SlaBreachesAt *string `json:"slaBreachesAt"`
	// [Internal] The time at which the issue's SLA was started.
	SlaStartedAt *string `json:"slaStartedAt"`
	// The SLA day count type for the issue. Whether SLA should be business days only or calendar days (default).
	SlaType *SLADayCountType `json:"slaType"`
	// The position of the issue related to other issues.
	SortOrder *float64 `json:"sortOrder"`
	// The comment the issue is created from.
	SourceCommentId *string `json:"sourceCommentId"`
	// [Internal] The pull request comment the issue is created from.
	SourcePullRequestCommentId *string `json:"sourcePullRequestCommentId"`
	// The team state of the issue.
	StateId *string `json:"stateId"`
	// The position of the issue in parent's sub-issue list.
	SubIssueSortOrder *float64 `json:"subIssueSortOrder"`
	// The identifiers of the users subscribing to this ticket.
	SubscriberIds []string `json:"subscriberIds"`
	// The identifier of the team associated with the issue.
	TeamId string `json:"teamId"`
	// The identifier of a template the issue should be created from. If other values are provided in the input, they will override template values.
	TemplateId *string `json:"templateId"`
	// The title of the issue.
	Title *string `json:"title"`
	// Whether to use the default template for the team. When set to true, the default template of this team based on user's membership will be applied.
	UseDefaultTemplate *bool `json:"useDefaultTemplate"`
}

// GetAssigneeId returns IssueCreateInput.AssigneeId, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetAssigneeId() *string { return v.AssigneeId }

// GetCompletedAt returns IssueCreateInput.CompletedAt, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetCompletedAt() *string { return v.CompletedAt }

// GetCreateAsUser returns IssueCreateInput.CreateAsUser, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetCreateAsUser() *string { return v.CreateAsUser }

// GetCreatedAt returns IssueCreateInput.CreatedAt, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetCreatedAt() *string { return v.CreatedAt }

// GetCycleId returns IssueCreateInput.CycleId, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetCycleId() *string { return v.CycleId }

// GetDelegateId returns IssueCreateInput.DelegateId, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetDelegateId() *string { return v.DelegateId }

// GetDescription returns IssueCreateInput.Description, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetDescription() *string { return v.Description }

// GetDescriptionData returns IssueCreateInput.DescriptionData, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetDescriptionData() *any { return v.DescriptionData }

// GetDisplayIconUrl returns IssueCreateInput.DisplayIconUrl, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetDisplayIconUrl() *string { return v.DisplayIconUrl }

// GetDueDate returns IssueCreateInput.DueDate, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetDueDate() *string { return v.DueDate }

// GetEstimate returns IssueCreateInput.Estimate, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetEstimate() *int { return v.Estimate }

// GetId returns IssueCreateInput.Id, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetId() *string { return v.Id }

// GetInheritsSharedAccess returns IssueCreateInput.InheritsSharedAccess, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetInheritsSharedAccess() *bool { return v.InheritsSharedAccess }

// GetLabelIds returns IssueCreateInput.LabelIds, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetLabelIds() []string { return v.LabelIds }

// GetLastAppliedTemplateId returns IssueCreateInput.LastAppliedTemplateId, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetLastAppliedTemplateId() *string { return v.LastAppliedTemplateId }

// GetParentId returns IssueCreateInput.ParentId, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetParentId() *string { return v.ParentId }

// GetPreserveSortOrderOnCreate returns IssueCreateInput.PreserveSortOrderOnCreate, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetPreserveSortOrderOnCreate() *bool { return v.PreserveSortOrderOnCreate }

// GetPriority returns IssueCreateInput.Priority, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetPriority() *int { return v.Priority }

// GetPrioritySortOrder returns IssueCreateInput.PrioritySortOrder, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetPrioritySortOrder() *float64 { return v.PrioritySortOrder }

// GetProjectId returns IssueCreateInput.ProjectId, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetProjectId() *string { return v.ProjectId }

// GetProjectMilestoneId returns IssueCreateInput.ProjectMilestoneId, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetProjectMilestoneId() *string { return v.ProjectMilestoneId }

// GetReferenceCommentId returns IssueCreateInput.ReferenceCommentId, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetReferenceCommentId() *string { return v.ReferenceCommentId }

// GetReleaseIds returns IssueCreateInput.ReleaseIds, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetReleaseIds() []string { return v.ReleaseIds }

// GetSlaBreachesAt returns IssueCreateInput.SlaBreachesAt, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetSlaBreachesAt() *string { return v.SlaBreachesAt }

// GetSlaStartedAt returns IssueCreateInput.SlaStartedAt, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetSlaStartedAt() *string { return v.SlaStartedAt }

// GetSlaType returns IssueCreateInput.SlaType, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetSlaType() *SLADayCountType { return v.SlaType }

// GetSortOrder returns IssueCreateInput.SortOrder, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetSortOrder() *float64 { return v.SortOrder }

// GetSourceCommentId returns IssueCreateInput.SourceCommentId, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetSourceCommentId() *string { return v.SourceCommentId }

// GetSourcePullRequestCommentId returns IssueCreateInput.SourcePullRequestCommentId, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetSourcePullRequestCommentId() *string {
	return v.SourcePullRequestCommentId
}

// GetStateId returns IssueCreateInput.StateId, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetStateId() *string { return v.StateId }

// GetSubIssueSortOrder returns IssueCreateInput.SubIssueSortOrder, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetSubIssueSortOrder() *float64 { return v.SubIssueSortOrder }

// GetSubscriberIds returns IssueCreateInput.SubscriberIds, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetSubscriberIds() []string { return v.SubscriberIds }

// GetTeamId returns IssueCreateInput.TeamId, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetTeamId() string { return v.TeamId }

// GetTemplateId returns IssueCreateInput.TemplateId, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetTemplateId() *string { return v.TemplateId }

// GetTitle returns IssueCreateInput.Title, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetTitle() *string { return v.Title }

// GetUseDefaultTemplate returns IssueCreateInput.UseDefaultTemplate, and is useful for accessing the field via an interface.
func (v *IssueCreateInput) GetUseDefaultTemplate() *bool { return v.UseDefaultTemplate }

// Input for creating a new label. A name is required. If no team is specified, the label is created as a workspace-level label available to all teams.
type IssueLabelCreateInput struct {
	// The color of the label.
	Color *string `json:"color"`
	// The description of the label.
	Description *string `json:"description"`
	// The identifier in UUID v4 format. If none is provided, the backend will generate one.
	Id *string `json:"id"`
	// Whether the label is a group.
	IsGroup *bool `json:"isGroup"`
	// The name of the label.
	Name string `json:"name"`
	// The identifier of the parent label.
	ParentId *string `json:"parentId"`
	// The time at which the label was retired. Set to null to restore a retired label.
	RetiredAt *string `json:"retiredAt"`
	// The team associated with the label. If not given, the label will be associated with the entire workspace.
	TeamId *string `json:"teamId"`
}

// GetColor returns IssueLabelCreateInput.Color, and is useful for accessing the field via an interface.
func (v *IssueLabelCreateInput) GetColor() *string { return v.Color }

// GetDescription returns IssueLabelCreateInput.Description, and is useful for accessing the field via an interface.
func (v *IssueLabelCreateInput) GetDescription() *string { return v.Description }

// GetId returns IssueLabelCreateInput.Id, and is useful for accessing the field via an interface.
func (v *IssueLabelCreateInput) GetId() *string { return v.Id }

// GetIsGroup returns IssueLabelCreateInput.IsGroup, and is useful for accessing the field via an interface.
func (v *IssueLabelCreateInput) GetIsGroup() *bool { return v.IsGroup }

// GetName returns IssueLabelCreateInput.Name, and is useful for accessing the field via an interface.
func (v *IssueLabelCreateInput) GetName() string { return v.Name }

// GetParentId returns IssueLabelCreateInput.ParentId, and is useful for accessing the field via an interface.
func (v *IssueLabelCreateInput) GetParentId() *string { return v.ParentId }

// GetRetiredAt returns IssueLabelCreateInput.RetiredAt, and is useful for accessing the field via an interface.
func (v *IssueLabelCreateInput) GetRetiredAt() *string { return v.RetiredAt }

// GetTeamId returns IssueLabelCreateInput.TeamId, and is useful for accessing the field via an interface.
func (v *IssueLabelCreateInput) GetTeamId() *string { return v.TeamId }

// ListTeamsResponse is returned by ListTeams on success.
type ListTeamsResponse struct {
	// All teams whose issues the user can access. This includes public teams and private teams the user is a member of. This may differ from `administrableTeams`, which returns teams whose settings the user can change but whose issues they don't necessarily have access to.
	Teams ListTeamsTeamsTeamConnection `json:"teams"`
}

// GetTeams returns ListTeamsResponse.Teams, and is useful for accessing the field via an interface.
func (v *ListTeamsResponse) GetTeams() ListTeamsTeamsTeamConnection { return v.Teams }

// ListTeamsTeamsTeamConnection includes the requested fields of the GraphQL type TeamConnection.
type ListTeamsTeamsTeamConnection struct {
	Nodes    []ListTeamsTeamsTeamConnectionNodesTeam `json:"nodes"`
	PageInfo ListTeamsTeamsTeamConnectionPageInfo    `json:"pageInfo"`
}

// GetNodes returns ListTeamsTeamsTeamConnection.Nodes, and is useful for accessing the field via an interface.
func (v *ListTeamsTeamsTeamConnection) GetNodes() []ListTeamsTeamsTeamConnectionNodesTeam {
	return v.Nodes
}

// GetPageInfo returns ListTeamsTeamsTeamConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *ListTeamsTeamsTeamConnection) GetPageInfo() ListTeamsTeamsTeamConnectionPageInfo {
	return v.PageInfo
}

// ListTeamsTeamsTeamConnectionNodesTeam includes the requested fields of the GraphQL type Team.
// The GraphQL type's documentation follows.
//
// A team is the primary organizational unit in Linear. Issues belong to teams, and each team has its own workflow states, cycles, labels, and settings. Teams can be public (visible to all workspace members), private (visible only to team members), or restricted (visible only within an enclosing private-team boundary). Teams can also have sub-teams that inherit settings from their parent.
type ListTeamsTeamsTeamConnectionNodesTeam struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// The team's unique key, used as a prefix in issue identifiers (e.g., 'ENG' in 'ENG-123') and in URLs.
	Key string `json:"key"`
	// The team's name.
	Name string `json:"name"`
}

// GetId returns ListTeamsTeamsTeamConnectionNodesTeam.Id, and is useful for accessing the field via an interface.
func (v *ListTeamsTeamsTeamConnectionNodesTeam) GetId() string { return v.Id }

// GetKey returns ListTeamsTeamsTeamConnectionNodesTeam.Key, and is useful for accessing the field via an interface.
func (v *ListTeamsTeamsTeamConnectionNodesTeam) GetKey() string { return v.Key }

// GetName returns ListTeamsTeamsTeamConnectionNodesTeam.Name, and is useful for accessing the field via an interface.
func (v *ListTeamsTeamsTeamConnectionNodesTeam) GetName() string { return v.Name }

// ListTeamsTeamsTeamConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
type ListTeamsTeamsTeamConnectionPageInfo struct {
	// Indicates if there are more results when paginating forward.
	HasNextPage bool `json:"hasNextPage"`
	// Cursor representing the last result in the paginated results.
	EndCursor *string `json:"endCursor"`
}

// GetHasNextPage returns ListTeamsTeamsTeamConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *ListTeamsTeamsTeamConnectionPageInfo) GetHasNextPage() bool { return v.HasNextPage }

// GetEndCursor returns ListTeamsTeamsTeamConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *ListTeamsTeamsTeamConnectionPageInfo) GetEndCursor() *string { return v.EndCursor }

// [Internal] The scope of product intelligence suggestion data for a team.
type ProductIntelligenceScope string

const (
	ProductIntelligenceScopeNone          ProductIntelligenceScope = "none"
	ProductIntelligenceScopeTeam          ProductIntelligenceScope = "team"
	ProductIntelligenceScopeTeamhierarchy ProductIntelligenceScope = "teamHierarchy"
	ProductIntelligenceScopeWorkspace     ProductIntelligenceScope = "workspace"
)

var AllProductIntelligenceScope = []ProductIntelligenceScope{
	ProductIntelligenceScopeNone,
	ProductIntelligenceScopeTeam,
	ProductIntelligenceScopeTeamhierarchy,
	ProductIntelligenceScopeWorkspace,
}

// ResolveTeamResponse is returned by ResolveTeam on success.
type ResolveTeamResponse struct {
	// All teams whose issues the user can access. This includes public teams and private teams the user is a member of. This may differ from `administrableTeams`, which returns teams whose settings the user can change but whose issues they don't necessarily have access to.
	Teams ResolveTeamTeamsTeamConnection `json:"teams"`
}

// GetTeams returns ResolveTeamResponse.Teams, and is useful for accessing the field via an interface.
func (v *ResolveTeamResponse) GetTeams() ResolveTeamTeamsTeamConnection { return v.Teams }

// ResolveTeamTeamsTeamConnection includes the requested fields of the GraphQL type TeamConnection.
type ResolveTeamTeamsTeamConnection struct {
	Nodes []ResolveTeamTeamsTeamConnectionNodesTeam `json:"nodes"`
}

// GetNodes returns ResolveTeamTeamsTeamConnection.Nodes, and is useful for accessing the field via an interface.
func (v *ResolveTeamTeamsTeamConnection) GetNodes() []ResolveTeamTeamsTeamConnectionNodesTeam {
	return v.Nodes
}

// ResolveTeamTeamsTeamConnectionNodesTeam includes the requested fields of the GraphQL type Team.
// The GraphQL type's documentation follows.
//
// A team is the primary organizational unit in Linear. Issues belong to teams, and each team has its own workflow states, cycles, labels, and settings. Teams can be public (visible to all workspace members), private (visible only to team members), or restricted (visible only within an enclosing private-team boundary). Teams can also have sub-teams that inherit settings from their parent.
type ResolveTeamTeamsTeamConnectionNodesTeam struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// The team's unique key, used as a prefix in issue identifiers (e.g., 'ENG' in 'ENG-123') and in URLs.
	Key string `json:"key"`
	// The team's name.
	Name string `json:"name"`
}

// GetId returns ResolveTeamTeamsTeamConnectionNodesTeam.Id, and is useful for accessing the field via an interface.
func (v *ResolveTeamTeamsTeamConnectionNodesTeam) GetId() string { return v.Id }

// GetKey returns ResolveTeamTeamsTeamConnectionNodesTeam.Key, and is useful for accessing the field via an interface.
func (v *ResolveTeamTeamsTeamConnectionNodesTeam) GetKey() string { return v.Key }

// GetName returns ResolveTeamTeamsTeamConnectionNodesTeam.Name, and is useful for accessing the field via an interface.
func (v *ResolveTeamTeamsTeamConnectionNodesTeam) GetName() string { return v.Name }

// Which day count to use for SLA calculations.
type SLADayCountType string

const (
	SLADayCountTypeAll              SLADayCountType = "all"
	SLADayCountTypeOnlybusinessdays SLADayCountType = "onlyBusinessDays"
)

var AllSLADayCountType = []SLADayCountType{
	SLADayCountTypeAll,
	SLADayCountTypeOnlybusinessdays,
}

type TeamCreateInput struct {
	// Period after which closed (completed, canceled, or duplicate) issues are automatically archived, in months. 0 means disabled.
	AutoArchivePeriod *float64 `json:"autoArchivePeriod"`
	// Period after which issues are automatically closed, in months.
	AutoClosePeriod *float64 `json:"autoClosePeriod"`
	// The canceled workflow state which auto closed issues will be set to.
	AutoCloseStateId *string `json:"autoCloseStateId"`
	// The color of the team.
	Color *string `json:"color"`
	// The cooldown time after each cycle in weeks.
	CycleCooldownTime *int `json:"cycleCooldownTime"`
	// The duration of each cycle in weeks.
	CycleDuration *int `json:"cycleDuration"`
	// Auto assign completed issues to current active cycle setting.
	CycleIssueAutoAssignCompleted *bool `json:"cycleIssueAutoAssignCompleted"`
	// Auto assign started issues to current active cycle setting.
	CycleIssueAutoAssignStarted *bool `json:"cycleIssueAutoAssignStarted"`
	// Only allow issues issues with cycles in Active Issues.
	CycleLockToActive *bool `json:"cycleLockToActive"`
	// The day of the week that a new cycle starts.
	CycleStartDay *float64 `json:"cycleStartDay"`
	// Whether the team uses cycles.
	CyclesEnabled *bool `json:"cyclesEnabled"`
	// What to use as an default estimate for unestimated issues.
	DefaultIssueEstimate *float64 `json:"defaultIssueEstimate"`
	// The identifier of the default project template of this team.
	DefaultProjectTemplateId *string `json:"defaultProjectTemplateId"`
	// The identifier of the default template for members of this team.
	DefaultTemplateForMembersId *string `json:"defaultTemplateForMembersId"`
	// The identifier of the default template for non-members of this team.
	DefaultTemplateForNonMembersId *string `json:"defaultTemplateForNonMembersId"`
	// The description of the team.
	Description *string `json:"description"`
	// Whether to group recent issue history entries.
	GroupIssueHistory *bool `json:"groupIssueHistory"`
	// The icon of the team.
	Icon *string `json:"icon"`
	// The identifier in UUID v4 format. If none is provided, the backend will generate one.
	Id *string `json:"id"`
	// Whether the team should inherit estimation settings from its parent. Only applies to sub-teams.
	InheritIssueEstimation *bool `json:"inheritIssueEstimation"`
	// [Internal] Whether the team should inherit its product intelligence scope from its parent. Only applies to sub-teams.
	InheritProductIntelligenceScope *bool `json:"inheritProductIntelligenceScope"`
	// [Internal] Whether the team should inherit its Slack auto-create project channel setting from its parent. Only applies to sub-teams.
	InheritSlackAutoCreateProjectChannel *bool `json:"inheritSlackAutoCreateProjectChannel"`
	// [Internal] Whether the team should inherit workflow statuses from its parent.
	InheritWorkflowStatuses *bool `json:"inheritWorkflowStatuses"`
	// [ALPHA] Whether initiatives are shown in the team's sidebar.
	InitiativesEnabled *bool `json:"initiativesEnabled"`
	// Whether to allow zeros in issues estimates.
	IssueEstimationAllowZero *bool `json:"issueEstimationAllowZero"`
	// Whether to add additional points to the estimate scale.
	IssueEstimationExtended *bool `json:"issueEstimationExtended"`
	// The issue estimation type to use. Must be one of "notUsed", "exponential", "fibonacci", "linear", "tShirt".
	IssueEstimationType *string `json:"issueEstimationType"`
	// Whether issue sharing is enabled for this team.
	IssueSharingEnabled *bool `json:"issueSharingEnabled"`
	// The key of the team. If not given, the key will be generated based on the name of the team.
	Key *string `json:"key"`
	// The name of the team.
	Name string `json:"name"`
	// The parent team ID.
	ParentId *string `json:"parentId"`
	// Internal. Whether the team is private or not.
	Private *bool `json:"private"`
	// [Internal] The scope of product intelligence suggestion data for the team.
	ProductIntelligenceScope *ProductIntelligenceScope `json:"productIntelligenceScope"`
	// Whether an issue needs to have a priority set before leaving triage.
	RequirePriorityToLeaveTriage *bool `json:"requirePriorityToLeaveTriage"`
	// Whether to move issues to bottom of the column when changing state.
	SetIssueSortOrderOnStateChange *string `json:"setIssueSortOrderOnStateChange"`
	// [Internal] Whether to automatically create a Slack channel when a new project is created in this team.
	SlackAutoCreateProjectChannel *bool `json:"slackAutoCreateProjectChannel"`
	// The timezone of the team.
	Timezone *string `json:"timezone"`
	// Whether triage mode is enabled for the team.
	TriageEnabled *bool `json:"triageEnabled"`
	// How many upcoming cycles to create.
	UpcomingCycleCount *float64 `json:"upcomingCycleCount"`
}

// GetAutoArchivePeriod returns TeamCreateInput.AutoArchivePeriod, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetAutoArchivePeriod() *float64 { return v.AutoArchivePeriod }

// GetAutoClosePeriod returns TeamCreateInput.AutoClosePeriod, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetAutoClosePeriod() *float64 { return v.AutoClosePeriod }

// GetAutoCloseStateId returns TeamCreateInput.AutoCloseStateId, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetAutoCloseStateId() *string { return v.AutoCloseStateId }

// GetColor returns TeamCreateInput.Color, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetColor() *string { return v.Color }

// GetCycleCooldownTime returns TeamCreateInput.CycleCooldownTime, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetCycleCooldownTime() *int { return v.CycleCooldownTime }

// GetCycleDuration returns TeamCreateInput.CycleDuration, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetCycleDuration() *int { return v.CycleDuration }

// GetCycleIssueAutoAssignCompleted returns TeamCreateInput.CycleIssueAutoAssignCompleted, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetCycleIssueAutoAssignCompleted() *bool {
	return v.CycleIssueAutoAssignCompleted
}

// GetCycleIssueAutoAssignStarted returns TeamCreateInput.CycleIssueAutoAssignStarted, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetCycleIssueAutoAssignStarted() *bool {
	return v.CycleIssueAutoAssignStarted
}

// GetCycleLockToActive returns TeamCreateInput.CycleLockToActive, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetCycleLockToActive() *bool { return v.CycleLockToActive }

// GetCycleStartDay returns TeamCreateInput.CycleStartDay, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetCycleStartDay() *float64 { return v.CycleStartDay }

// GetCyclesEnabled returns TeamCreateInput.CyclesEnabled, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetCyclesEnabled() *bool { return v.CyclesEnabled }

// GetDefaultIssueEstimate returns TeamCreateInput.DefaultIssueEstimate, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetDefaultIssueEstimate() *float64 { return v.DefaultIssueEstimate }

// GetDefaultProjectTemplateId returns TeamCreateInput.DefaultProjectTemplateId, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetDefaultProjectTemplateId() *string { return v.DefaultProjectTemplateId }

// GetDefaultTemplateForMembersId returns TeamCreateInput.DefaultTemplateForMembersId, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetDefaultTemplateForMembersId() *string {
	return v.DefaultTemplateForMembersId
}

// GetDefaultTemplateForNonMembersId returns TeamCreateInput.DefaultTemplateForNonMembersId, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetDefaultTemplateForNonMembersId() *string {
	return v.DefaultTemplateForNonMembersId
}

// GetDescription returns TeamCreateInput.Description, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetDescription() *string { return v.Description }

// GetGroupIssueHistory returns TeamCreateInput.GroupIssueHistory, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetGroupIssueHistory() *bool { return v.GroupIssueHistory }

// GetIcon returns TeamCreateInput.Icon, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetIcon() *string { return v.Icon }

// GetId returns TeamCreateInput.Id, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetId() *string { return v.Id }

// GetInheritIssueEstimation returns TeamCreateInput.InheritIssueEstimation, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetInheritIssueEstimation() *bool { return v.InheritIssueEstimation }

// GetInheritProductIntelligenceScope returns TeamCreateInput.InheritProductIntelligenceScope, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetInheritProductIntelligenceScope() *bool {
	return v.InheritProductIntelligenceScope
}

// GetInheritSlackAutoCreateProjectChannel returns TeamCreateInput.InheritSlackAutoCreateProjectChannel, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetInheritSlackAutoCreateProjectChannel() *bool {
	return v.InheritSlackAutoCreateProjectChannel
}

// GetInheritWorkflowStatuses returns TeamCreateInput.InheritWorkflowStatuses, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetInheritWorkflowStatuses() *bool { return v.InheritWorkflowStatuses }

// GetInitiativesEnabled returns TeamCreateInput.InitiativesEnabled, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetInitiativesEnabled() *bool { return v.InitiativesEnabled }

// GetIssueEstimationAllowZero returns TeamCreateInput.IssueEstimationAllowZero, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetIssueEstimationAllowZero() *bool { return v.IssueEstimationAllowZero }

// GetIssueEstimationExtended returns TeamCreateInput.IssueEstimationExtended, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetIssueEstimationExtended() *bool { return v.IssueEstimationExtended }

// GetIssueEstimationType returns TeamCreateInput.IssueEstimationType, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetIssueEstimationType() *string { return v.IssueEstimationType }

// GetIssueSharingEnabled returns TeamCreateInput.IssueSharingEnabled, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetIssueSharingEnabled() *bool { return v.IssueSharingEnabled }

// GetKey returns TeamCreateInput.Key, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetKey() *string { return v.Key }

// GetName returns TeamCreateInput.Name, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetName() string { return v.Name }

// GetParentId returns TeamCreateInput.ParentId, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetParentId() *string { return v.ParentId }

// GetPrivate returns TeamCreateInput.Private, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetPrivate() *bool { return v.Private }

// GetProductIntelligenceScope returns TeamCreateInput.ProductIntelligenceScope, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetProductIntelligenceScope() *ProductIntelligenceScope {
	return v.ProductIntelligenceScope
}

// GetRequirePriorityToLeaveTriage returns TeamCreateInput.RequirePriorityToLeaveTriage, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetRequirePriorityToLeaveTriage() *bool {
	return v.RequirePriorityToLeaveTriage
}

// GetSetIssueSortOrderOnStateChange returns TeamCreateInput.SetIssueSortOrderOnStateChange, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetSetIssueSortOrderOnStateChange() *string {
	return v.SetIssueSortOrderOnStateChange
}

// GetSlackAutoCreateProjectChannel returns TeamCreateInput.SlackAutoCreateProjectChannel, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetSlackAutoCreateProjectChannel() *bool {
	return v.SlackAutoCreateProjectChannel
}

// GetTimezone returns TeamCreateInput.Timezone, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetTimezone() *string { return v.Timezone }

// GetTriageEnabled returns TeamCreateInput.TriageEnabled, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetTriageEnabled() *bool { return v.TriageEnabled }

// GetUpcomingCycleCount returns TeamCreateInput.UpcomingCycleCount, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetUpcomingCycleCount() *float64 { return v.UpcomingCycleCount }

// ViewerWhoamiResponse is returned by ViewerWhoami on success.
type ViewerWhoamiResponse struct {
	// The currently authenticated user making the API request.
	Viewer ViewerWhoamiViewerUser `json:"viewer"`
}

// GetViewer returns ViewerWhoamiResponse.Viewer, and is useful for accessing the field via an interface.
func (v *ViewerWhoamiResponse) GetViewer() ViewerWhoamiViewerUser { return v.Viewer }

// ViewerWhoamiViewerUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user that belongs to a workspace. Users can have different roles (admin, member, guest, or app) that determine their level of access. Users can be members of multiple teams, and can be active or deactivated. Guest users have limited access scoped to specific teams they are invited to.
type ViewerWhoamiViewerUser struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// The user's full name.
	Name string `json:"name"`
	// The user's display (nick) name. Must be unique within the workspace.
	DisplayName string `json:"displayName"`
	// The user's email address.
	Email string `json:"email"`
	// Whether the user is a workspace administrator. On Free plans, all members are treated as admins.
	Admin bool `json:"admin"`
	// Whether the user is a guest in the workspace and limited to accessing a subset of teams.
	Guest bool `json:"guest"`
	// The workspace that the user belongs to.
	Organization ViewerWhoamiViewerUserOrganization `json:"organization"`
}

// GetId returns ViewerWhoamiViewerUser.Id, and is useful for accessing the field via an interface.
func (v *ViewerWhoamiViewerUser) GetId() string { return v.Id }

// GetName returns ViewerWhoamiViewerUser.Name, and is useful for accessing the field via an interface.
func (v *ViewerWhoamiViewerUser) GetName() string { return v.Name }

// GetDisplayName returns ViewerWhoamiViewerUser.DisplayName, and is useful for accessing the field via an interface.
func (v *ViewerWhoamiViewerUser) GetDisplayName() string { return v.DisplayName }

// GetEmail returns ViewerWhoamiViewerUser.Email, and is useful for accessing the field via an interface.
func (v *ViewerWhoamiViewerUser) GetEmail() string { return v.Email }

// GetAdmin returns ViewerWhoamiViewerUser.Admin, and is useful for accessing the field via an interface.
func (v *ViewerWhoamiViewerUser) GetAdmin() bool { return v.Admin }

// GetGuest returns ViewerWhoamiViewerUser.Guest, and is useful for accessing the field via an interface.
func (v *ViewerWhoamiViewerUser) GetGuest() bool { return v.Guest }

// GetOrganization returns ViewerWhoamiViewerUser.Organization, and is useful for accessing the field via an interface.
func (v *ViewerWhoamiViewerUser) GetOrganization() ViewerWhoamiViewerUserOrganization {
	return v.Organization
}

// ViewerWhoamiViewerUserOrganization includes the requested fields of the GraphQL type Organization.
// The GraphQL type's documentation follows.
//
// A workspace (referred to as Organization in the API). Workspaces are the root-level container for all teams, users, projects, issues, and settings. Every user belongs to at least one workspace, and all data is scoped within a workspace boundary.
type ViewerWhoamiViewerUserOrganization struct {
	// The workspace's name.
	Name string `json:"name"`
	// The workspace's unique URL key, used in URLs to identify the workspace.
	UrlKey string `json:"urlKey"`
}

// GetName returns ViewerWhoamiViewerUserOrganization.Name, and is useful for accessing the field via an interface.
func (v *ViewerWhoamiViewerUserOrganization) GetName() string { return v.Name }

// GetUrlKey returns ViewerWhoamiViewerUserOrganization.UrlKey, and is useful for accessing the field via an interface.
func (v *ViewerWhoamiViewerUserOrganization) GetUrlKey() string { return v.UrlKey }

// __ArchiveIssueInput is used internally by genqlient
type __ArchiveIssueInput struct {
	Id string `json:"id"`
}

// GetId returns __ArchiveIssueInput.Id, and is useful for accessing the field via an interface.
func (v *__ArchiveIssueInput) GetId() string { return v.Id }

// __CreateIssueInput is used internally by genqlient
type __CreateIssueInput struct {
	Input IssueCreateInput `json:"input"`
}

// GetInput returns __CreateIssueInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateIssueInput) GetInput() IssueCreateInput { return v.Input }

// __CreateIssueLabelInput is used internally by genqlient
type __CreateIssueLabelInput struct {
	Input IssueLabelCreateInput `json:"input"`
}

// GetInput returns __CreateIssueLabelInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateIssueLabelInput) GetInput() IssueLabelCreateInput { return v.Input }

// __CreateTeamInput is used internally by genqlient
type __CreateTeamInput struct {
	Input TeamCreateInput `json:"input"`
}

// GetInput returns __CreateTeamInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateTeamInput) GetInput() TeamCreateInput { return v.Input }

// __GetIssueDetailsInput is used internally by genqlient
type __GetIssueDetailsInput struct {
	Id string `json:"id"`
}

// GetId returns __GetIssueDetailsInput.Id, and is useful for accessing the field via an interface.
func (v *__GetIssueDetailsInput) GetId() string { return v.Id }

// __GetIssueTitleURLInput is used internally by genqlient
type __GetIssueTitleURLInput struct {
	Id string `json:"id"`
}

// GetId returns __GetIssueTitleURLInput.Id, and is useful for accessing the field via an interface.
func (v *__GetIssueTitleURLInput) GetId() string { return v.Id }

// __ListTeamsInput is used internally by genqlient
type __ListTeamsInput struct {
	First *int    `json:"first"`
	After *string `json:"after"`
}

// GetFirst returns __ListTeamsInput.First, and is useful for accessing the field via an interface.
func (v *__ListTeamsInput) GetFirst() *int { return v.First }

// GetAfter returns __ListTeamsInput.After, and is useful for accessing the field via an interface.
func (v *__ListTeamsInput) GetAfter() *string { return v.After }

// __ResolveTeamInput is used internally by genqlient
type __ResolveTeamInput struct {
	Reference string `json:"reference"`
}

// GetReference returns __ResolveTeamInput.Reference, and is useful for accessing the field via an interface.
func (v *__ResolveTeamInput) GetReference() string { return v.Reference }

// The mutation executed by ArchiveIssue.
const ArchiveIssue_Operation = `
mutation ArchiveIssue ($id: String!) {
	issueArchive(id: $id) {
		success
	}
}
`

func ArchiveIssue(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *ArchiveIssueResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ArchiveIssue",
		Query:  ArchiveIssue_Operation,
		Variables: &__ArchiveIssueInput{
			Id: id,
		},
	}

	data_ = &ArchiveIssueResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by CreateIssue.
const CreateIssue_Operation = `
mutation CreateIssue ($input: IssueCreateInput!) {
	issueCreate(input: $input) {
		success
		issue {
			id
			identifier
			url
			title
			team {
				key
			}
		}
	}
}
`

func CreateIssue(
	ctx_ context.Context,
	client_ graphql.Client,
	input IssueCreateInput,
) (data_ *CreateIssueResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateIssue",
		Query:  CreateIssue_Operation,
		Variables: &__CreateIssueInput{
			Input: input,
		},
	}

	data_ = &CreateIssueResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by CreateIssueLabel.
const CreateIssueLabel_Operation = `
mutation CreateIssueLabel ($input: IssueLabelCreateInput!) {
	issueLabelCreate(input: $input) {
		success
		issueLabel {
			id
			name
			color
			description
			team {
				key
				name
			}
		}
	}
}
`

func CreateIssueLabel(
	ctx_ context.Context,
	client_ graphql.Client,
	input IssueLabelCreateInput,
) (data_ *CreateIssueLabelResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateIssueLabel",
		Query:  CreateIssueLabel_Operation,
		Variables: &__CreateIssueLabelInput{
			Input: input,
		},
	}

	data_ = &CreateIssueLabelResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by CreateTeam.
const CreateTeam_Operation = `
mutation CreateTeam ($input: TeamCreateInput!) {
	teamCreate(input: $input) {
		success
		team {
			id
			key
			name
		}
	}
}
`

func CreateTeam(
	ctx_ context.Context,
	client_ graphql.Client,
	input TeamCreateInput,
) (data_ *CreateTeamResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateTeam",
		Query:  CreateTeam_Operation,
		Variables: &__CreateTeamInput{
			Input: input,
		},
	}

	data_ = &CreateTeamResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetIssueDetails.
const GetIssueDetails_Operation = `
query GetIssueDetails ($id: String!) {
	issue(id: $id) {
		identifier
		title
		description
		url
		branchName
		state {
			name
			color
		}
		assignee {
			name
			displayName
		}
		priority
		project {
			name
		}
		projectMilestone {
			name
		}
		cycle {
			id
			number
			name
			isActive
			isNext
			isPrevious
			isFuture
			isPast
		}
		team {
			activeCycle {
				number
			}
		}
		labels(first: 50) {
			nodes {
				id
				name
				color
			}
		}
		parent {
			identifier
			title
			state {
				name
				color
			}
		}
		children(first: 250) {
			nodes {
				identifier
				title
				state {
					name
					color
				}
			}
		}
		attachments(first: 50) {
			nodes {
				id
				title
				url
				subtitle
				sourceType
				metadata
				createdAt
			}
		}
		documents(first: 50) {
			nodes {
				id
				title
				slugId
				url
				createdAt
				updatedAt
			}
		}
	}
}
`

func GetIssueDetails(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *GetIssueDetailsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetIssueDetails",
		Query:  GetIssueDetails_Operation,
		Variables: &__GetIssueDetailsInput{
			Id: id,
		},
	}

	data_ = &GetIssueDetailsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetIssueTitleURL.
const GetIssueTitleURL_Operation = `
query GetIssueTitleURL ($id: String!) {
	issue(id: $id) {
		title
		url
		identifier
	}
}
`

func GetIssueTitleURL(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *GetIssueTitleURLResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetIssueTitleURL",
		Query:  GetIssueTitleURL_Operation,
		Variables: &__GetIssueTitleURLInput{
			Id: id,
		},
	}

	data_ = &GetIssueTitleURLResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ListTeams.
const ListTeams_Operation = `
query ListTeams ($first: Int, $after: String) {
	teams(first: $first, after: $after) {
		nodes {
			id
			key
			name
		}
		pageInfo {
			hasNextPage
			endCursor
		}
	}
}
`

func ListTeams(
	ctx_ context.Context,
	client_ graphql.Client,
	first *int,
	after *string,
) (data_ *ListTeamsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ListTeams",
		Query:  ListTeams_Operation,
		Variables: &__ListTeamsInput{
			First: first,
			After: after,
		},
	}

	data_ = &ListTeamsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ResolveTeam.
const ResolveTeam_Operation = `
query ResolveTeam ($reference: String!) {
	teams(filter: {or:[{key:{eqIgnoreCase:$reference}},{name:{eqIgnoreCase:$reference}}]}) {
		nodes {
			id
			key
			name
		}
	}
}
`

func ResolveTeam(
	ctx_ context.Context,
	client_ graphql.Client,
	reference string,
) (data_ *ResolveTeamResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ResolveTeam",
		Query:  ResolveTeam_Operation,
		Variables: &__ResolveTeamInput{
			Reference: reference,
		},
	}

	data_ = &ResolveTeamResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ViewerWhoami.
const ViewerWhoami_Operation = `
query ViewerWhoami {
	viewer {
		id
		name
		displayName
		email
		admin
		guest
		organization {
			name
			urlKey
		}
	}
}
`

func ViewerWhoami(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *ViewerWhoamiResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ViewerWhoami",
		Query:  ViewerWhoami_Operation,
	}

	data_ = &ViewerWhoamiResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
